LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_CFLAGS += -DPLATFORM_ANDROID

LOCAL_MODULE := jdrtsp
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

LOCAL_C_INCLUDES := $(LOCAL_PATH)/.. 
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../logutil/include
MY_SRCS := ../src

LOCAL_SRC_FILES := $(MY_SRCS)/JdRtp.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRtcp.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdAuthRfc2617.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRfc2250.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRfc3640.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRfc3984.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRfc5391.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRtpRcv.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRtpSnd.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRtspClnt.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRtspClntRec.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdRtspSrv.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdMediaResMgr.cpp
LOCAL_SRC_FILES += $(MY_SRCS)/JdNetUtil.cpp

include $(BUILD_STATIC_LIBRARY)
