all:
	gcc -g -DUNIT_TEST_DEMUX filesrc.cpp xport.cpp  strmclock.cpp udprx.cpp ../../osal/src/JdOsal.cpp -I ../include -I ../../osal/include -I ../../../logutil/include -I ../../streamif/include -lstdc++ -lpthread -o testxport
