LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := onyxcore
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/..
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../codecdm81xx/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../logutil/include

LOCAL_CFLAGS += -DPLATFORM_ANDROID

LOCAL_SRC_FILES := ../src/AvMixer.cpp


include $(BUILD_STATIC_LIBRARY)
